### PR TITLE
Fix readme title

### PR DESCRIPTION
**Pull request by m3ller**

### CODE REVIEW

**Comment by randomir** [comment]
Is there a reason you used a PR here, instead of simply pushing the commit?

**Comment by m3ller** [comment]
No good reason other than the habit of not pushing directly to the master branch.

**Comment by m3ller** [comment]
I am assuming that you would suggest that I make the changes with GitHub GUI and commit/push the changes directly to master, is that correct? @randomir

**Comment by randomir** [comment]
Yes, I would suggest _trivial changes_* like this are pushed directly to master. You don't have to use GitHub/GUI at all.

I would say PRs are useful for:
- aggregating multiple commits in a single referenceable unit of work (bug fix, feature)
- documenting units of work, i.e. providing rationale or context, in relation to some opened issues
- providing forum for discussion and review

PRs are not useful and clutter the git history with zero information "merge commits" when they contain simple/uninteresting commits (commits that don't need to be reviewed, justified of referenced).

---

*) _trivial changes_: tweaks to readme/docs/comments/code formatting which do not require review and/or discussion forum (like pull request page).

**Pull request merged**
